# Generated by Django 2.2.17 on 2021-02-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
