# Generated by Django 2.2.17 on 2021-02-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPT', '0002_persons_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
