# Generated by Django 3.1.7 on 2021-03-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JPT', '0003_posts_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='ava',
        ),
        migrations.AddField(
            model_name='persons',
            name='ava',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JPT.media'),
        ),
    ]
