# Generated by Django 3.1.7 on 2021-03-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPT', '0005_auto_20210310_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
