# Generated by Django 3.1.7 on 2021-04-18 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JPT', '0006_posts_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appearence', models.DateTimeField(auto_now_add=True)),
                ('dialogPfoto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JPT.media')),
                ('listOfMembers', models.ManyToManyField(to='JPT.Persons')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appearence', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('atachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JPT.dialogs')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JPT.persons')),
                ('subphoto', models.ManyToManyField(to='JPT.Media')),
            ],
        ),
    ]
