# Generated by Django 3.1.7 on 2021-06-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JPT', '0007_auto_20210530_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='ava',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JPT.media'),
        ),
    ]
