# Generated by Django 3.1.7 on 2021-04-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPT', '0007_dialogs_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogs',
            name='dialogname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
