# Generated by Django 3.1.7 on 2021-04-24 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JPT', '0008_dialogs_dialogname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='login',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='password',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='second_name',
        ),
        migrations.AddField(
            model_name='persons',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
