# Generated by Django 3.1.7 on 2021-04-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPT', '0009_auto_20210424_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='date_of_appearence',
            field=models.DateField(null=True),
        ),
    ]
