# Generated by Django 2.2.17 on 2021-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPT', '0016_auto_20210205_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ava/'),
        ),
    ]
